"""Generate hd_constants.py from the OpenHaptics headers.

The HD API is a plain C API, so ctypes needs the numeric values of the
HD_* enums.  Rather than transcribing them by hand (and getting one wrong
in a way that silently reads the wrong field), parse them out of the
installed SDK headers.

Usage:  python gen_constants.py [path\to\OpenHaptics\include]
"""

import os
import re
import sys

# Three shapes appear in the headers:
#   #define HD_CURRENT_POSITION   0x2050
#   #define HD_SUCCESS            0
#   #define HD_DEVICE_BUTTON_1    (1 << 0)      <- button masks, calibration flags
DEFINE = re.compile(
    r"^\s*#\s*define\s+(HD_[A-Z0-9_]+)\s+"
    r"(?:"
    r"\(?\s*(?P<num>0[xX][0-9a-fA-F]+|-?\d+)\s*\)?"
    r"|"
    r"\(\s*(?P<sh_lhs>\d+)\s*<<\s*(?P<sh_rhs>\d+)\s*\)"
    r")\s*(?:/\*|//|$)"
)

SEARCH_ROOTS = [
    r"C:\OpenHaptics\Developer\3.5.0\include",
    r"C:\OpenHaptics\Developer\3.4.0\include",
    r"C:\Program Files\3D Systems\OpenHaptics\Developer\3.5.0\include",
    r"C:\Program Files\OpenHaptics\Developer\3.5.0\include",
]


def find_include_dir(explicit=None):
    if explicit:
        if not os.path.isdir(explicit):
            raise SystemExit(f"not a directory: {explicit}")
        return explicit
    for root in SEARCH_ROOTS:
        if os.path.isfile(os.path.join(root, "HD", "hdDefines.h")):
            return root
    # Last resort: sweep the usual drives for hdDefines.h.
    for drive in ("C:\\", "D:\\", "E:\\"):
        for dirpath, dirnames, filenames in os.walk(drive):
            # Don't descend into places the SDK is never installed.
            dirnames[:] = [
                d for d in dirnames
                if d.lower() not in ("windows", "$recycle.bin", "system volume information")
            ]
            if "hdDefines.h" in filenames and os.path.basename(dirpath).upper() == "HD":
                return os.path.dirname(dirpath)
    raise SystemExit(
        "Could not find the OpenHaptics headers. Pass the include directory "
        "explicitly, e.g.\n"
        "    python gen_constants.py \"C:\OpenHaptics\Developer\3.5.0\include\""
    )


def main():
    include_dir = find_include_dir(sys.argv[1] if len(sys.argv) > 1 else None)
    hd_dir = os.path.join(include_dir, "HD")
    headers = sorted(
        os.path.join(hd_dir, f)
        for f in os.listdir(hd_dir)
        if f.lower().endswith(".h")
    )
    if not headers:
        raise SystemExit(f"no headers under {hd_dir}")

    seen = {}
    order = []
    for header in headers:
        with open(header, "r", encoding="utf-8", errors="replace") as fh:
            for line in fh:
                m = DEFINE.match(line)
                if not m:
                    continue
                name = m.group(1)
                if m.group("num") is not None:
                    raw = m.group("num")
                    value = int(raw, 0)
                else:
                    value = int(m.group("sh_lhs")) << int(m.group("sh_rhs"))
                    # Emit the shift as written; it documents the bit position.
                    raw = f"({m.group('sh_lhs')} << {m.group('sh_rhs')})"
                if name in seen:
                    continue
                seen[name] = value
                order.append((name, raw, value, os.path.basename(header)))

    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "hd_constants.py")
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write('"""HD API constants, generated by gen_constants.py. Do not edit."""\n\n')
        fh.write(f"# source: {include_dir}\n\n")
        current_header = None
        for name, raw, _value, header in order:
            if header != current_header:
                fh.write(f"\n# --- {header} ---\n")
                current_header = header
            fh.write(f"{name} = {raw}\n")
        # Reverse lookup for pretty-printing. Values collide (several enums
        # share 0 and 1), so keep the first name defined for each.
        fh.write("\n\nNAMES_BY_VALUE = {\n")
        emitted = set()
        for name, _raw, value, _header in order:
            if value in emitted:
                continue
            emitted.add(value)
            fh.write(f"    {value}: {name!r},\n")
        fh.write("}\n")

    print(f"wrote {out_path}: {len(order)} constants from {len(headers)} headers")


if __name__ == "__main__":
    main()
